# Generated by Django 3.2.7 on 2021-09-18 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'singer',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('is_delete', models.BooleanField(default=False)),
                ('singer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.singer')),
            ],
            options={
                'db_table': 'song',
            },
        ),
    ]
